# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
# .golangci.yaml

# Включаем линтеры по умолчанию
linters:
  enable:
    - gosimple
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - typecheck
    - bodyclose
    - gocritic
    - gofmt
    - goimports
    - revive
    - unconvert
    - gocyclo
    - misspell
    - prealloc
    - whitespace

# Настройки для линтеров
linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 10 # Минимальная сложность для выявления цикломатической сложности
  misspell:
    locale: US # Локаль для проверки орфографии

# Настройки запуска
run:
  skip-dirs:
    - vendor # Пропускаем директорию vendor
  skip-files:
    - ".*_test.go" # Пропускаем тестовые файлы (по желанию)
  tests: false # Не анализировать тестовые файлы

# Настройки вывода
output:
  format: colored-line-number # Формат вывода (можно изменить на json, text и др.)
  print-issued-lines: true
  print-linter-name: true

# Дополнительные настройки
issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 50